---
config:
  radar:
    curveTension: 0.0
    width: 256
    height: 256
    marginTop: 44
  themeVariables:
    fontSize: 20
    cScale0: "#BF5700"
title: "Soft Skills"
---
radar-beta
  axis m["Communication"], s["Work Ethic"], e["Leadership"]
  axis h["Time Management"], g["Flexibility"], a["Integrity"]
  curve karl{7, 9, 4, 5, 9, 10}

  max 10
  min 0
